import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 * 
 * @author Jatin Mamtani
 * 
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     * 
     * <html>
     * <head>
     * <title>the channel tag title as the page title</title>
     * </head>
     * <body>
     *  <h1>the page title inside a link to the <channel> link</h1>
     *  <p>the channel description</p>
     *  <table border="1">
     *   <tr>
     *    <th>Date</th>
     *    <th>Source</th>
     *    <th>News</th>
     *   </tr>
     * 
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        
        //searches for the title, description and link gives child
        int title = getChildElement(channel, "title");
        int description = getChildElement(channel, "description");
        int link = getChildElement(channel, "link");

        /*
         * The output will be "Empty child" if title tag has no children if it
         * does not have any child text. But if it has it will be assigned to a
         * string variable named titletag.
         */
        
        //condition for no title
        String titletag = "Empty Title";
        
        if (channel.child(title).numberOfChildren() == 1) {
            titletag = channel.child(title).child(0).label();
        }

        /*
         * If the child description does not have a child text the output will
         * be "No description". But if it contains a child it will be assigned
         * to the string variable desriptiontag.
         */

        String descriptiontag = "Empty description";
        if (channel.child(description).numberOfChildren() == 1) {
            descriptiontag = channel.child(description).child(0).label();
        }

        out.println("<html>");
        out.println("<head>");
        out.println("<title>" + titletag + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1><a href=\"" + channel.child(link).child(0).label()
                + "\">" + titletag + "</a></h1>");
        out.println("<p>" + descriptiontag + "</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file.  These are the
     * expected elements generated by this method:
     * 
     *  </table>
     * </body>
     * </html>
     * 
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     * 
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        
        
        int n = xml.numberOfChildren();
        int marker = -1;
        int m = 0;
        while (m < n) {
            if (xml.child(m).label().equals(tag)) {
                marker = m;
            }
            m++;
        }
        return marker;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     * 
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires
     * [the label of the root of item is an <item> tag] and out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("<tr>"); 

        String publishDatetag = "No date available";
        if (getChildElement(item, "pubDate") != -1) {
            publishDatetag = item.child(getChildElement(item, "pubDate")).child(0)
                    .label();    }
        
        out.println("<th>" + publishDatetag + "</th>");

        //if the source is present it will be added under source else no source message shown
        
        String sourcetag = "No source available";
        String sourceURL = "";
        if (getChildElement(item, "source") != -1) {
            sourcetag = item.child(getChildElement(item, "source")).child(0)
                    .label();
            sourceURL = item.child(getChildElement(item, "source"))
                    .attributeValue("url");
        }
        out.println("<td><a href = \"" + sourceURL + "\" >" + sourcetag
                + "</a></td>");

        
        //getting the element values for the title and description 
        int t = getChildElement(item, "title"); 
        int d = getChildElement(item, "description"); 
        
        
        String news = "No title available";
        if (d != -1 && item.child(d).numberOfChildren() == 1) {
            news = item.child(d).child(0).label();
        }
        if (t != -1 && item.child(t).numberOfChildren() == 1) {
            news = item.child(t).child(0).label();
        }
        int link = getChildElement(item, "link");
        String linkURL = "";
        if (link != -1) {
            linkURL = item.child(link).child(0).label();
        }
        out.println("<td><a href = \"" + linkURL + "\">" + news
                + "</a></td>\n</tr>");
    }
    

    /**
     * Main method.
     * 
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        //taking the rss link as input from the user
        out.println("Enter URL of a RSS 2.0 feed to get HTML page: ");
        String input = in.nextLine();
        XMLTree xml = new XMLTree1(input);

        while (!xml.label().equals("rss") && !xml.hasAttribute("version")
                && !xml.attributeValue("version").equals("2.0")) {
            out.print("\nInavlid, Try Again! ");
            input = in.nextLine();
            xml = new XMLTree1(input);
        }

        //printing the final html web page
        out.println("Enter the HTML file name with the html extension");
        String fileName = in.nextLine();

        SimpleWriter fileOut = new SimpleWriter1L(fileName);

        outputHeader(xml.child(0), fileOut);

        int i = 0;
        while (i < xml.child(0).numberOfChildren()) {
            if (xml.child(0).child(i).label().equals(("item"))) {
                processItem(xml.child(0).child(i), fileOut);
            }
            i++;
        }
        outputFooter(fileOut);

        fileOut.close();

        in.close();
        out.close();
    }

}